/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineJobBankSystem;

import java.awt.Color;

/**
 *
 * @author David
 */
public class applyToJob extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    OracleConnection DB;
    String user;
    String jobID;
    public applyToJob(OracleConnection DB, String user, String jobID) {
        this.user = user;
        this.DB = DB;
        this.jobID = jobID;
        System.out.println(user + "\n" + jobID);
        initComponents();
        jobInfo.setEditable(false);
        jobInfo.setFocusable(false);
        // Load in component for job ID
        String allInfo = DB.getJobInfo(jobID);
        jobInfo.setText(allInfo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        skills = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        workExperience = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        skillsInput = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        workExperienceInput = new javax.swing.JTextArea();
        msg = new javax.swing.JLabel();
        jobInfoDesc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jobInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));
        setForeground(new java.awt.Color(102, 255, 255));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fill in the details to submit your application");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CareerCove");

        skills.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        skills.setText("Skills");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        viewBtn.setText("Return to View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        workExperience.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        workExperience.setText("Work Experience");

        skillsInput.setColumns(20);
        skillsInput.setLineWrap(true);
        skillsInput.setRows(5);
        jScrollPane3.setViewportView(skillsInput);

        workExperienceInput.setColumns(20);
        workExperienceInput.setLineWrap(true);
        workExperienceInput.setRows(5);
        jScrollPane4.setViewportView(workExperienceInput);

        msg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jobInfoDesc.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jobInfoDesc.setText("Job Info");

        jobInfo.setColumns(20);
        jobInfo.setLineWrap(true);
        jobInfo.setRows(5);
        jScrollPane2.setViewportView(jobInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(workExperience)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(skills))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jobInfoDesc)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitBtn)
                                .addGap(24, 24, 24)
                                .addComponent(viewBtn))
                            .addComponent(msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jobInfoDesc)
                        .addGap(86, 86, 86)
                        .addComponent(skills)
                        .addGap(58, 58, 58)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(workExperience)))
                .addGap(18, 18, 18)
                .addComponent(msg, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submitBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        
        if (skills.getText().equals("") || workExperienceInput.getText().equals("")) {
            msg.setForeground(Color.RED);
            msg.setText("Error: there are missing fields, please fill in every field.");
            return;
        }
        
        boolean success = DB.submitApplication(user, skills.getText(), workExperience.getText(), jobID);
        if (success) {
            msg.setForeground(new Color(0, 128, 0));
            msg.setText("Application has been succesfully submitted.");
        } else {
            msg.setForeground(Color.RED);
            msg.setText("Error storing user's information.");
        }

        
    }//GEN-LAST:event_submitBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        ApplicantView newScreen = new ApplicantView(DB, user);
        newScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jobInfo;
    private javax.swing.JLabel jobInfoDesc;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel skills;
    private javax.swing.JTextArea skillsInput;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton viewBtn;
    private javax.swing.JLabel workExperience;
    private javax.swing.JTextArea workExperienceInput;
    // End of variables declaration//GEN-END:variables
}
