/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineJobBankSystem;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author David
 */
public class AvailableJobs extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    OracleConnection DB;
    String user;
    JList<String> listJobs;
    ArrayList<String> jobs;
    public AvailableJobs(OracleConnection DB, String user) {
        this.user = user;
        this.DB = DB;
        initComponents();
        this.setResizable(false);
        jobListings.setEditable(false);
        jobListings.setFocusable(false);
        
        // for recruiters, don't allow them to apply to jobs (disable option)
        if (DB.userType(user).equals("recruiter")) {
            applyJob.setEnabled(false);
        }
        
        
        // Create JList to add to existing JScrollPane1
        DefaultListModel<String> listModel = new DefaultListModel<>();
        listJobs = new JList<>(listModel);
        
        // Personalizing what each job elem will look like 
        listJobs.setFont(new Font("Arial", Font.PLAIN, 16));
        listJobs.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        // call function that fills in jpanel with information about the user 
        try {
            jobs = DB.getJobs();
            if (jobs.isEmpty()) {
                // means there are no jobs
                listModel.addElement("There are no jobs on the portal.");
            } else {
                for (String job : jobs) {
                    listModel.addElement(job);
                }
            }
            
            jScrollPane1.setViewportView(listJobs);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jobListings = new javax.swing.JTextPane();
        returnBtn = new javax.swing.JButton();
        applyJob = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));
        setForeground(new java.awt.Color(102, 255, 255));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CareerCove");

        jScrollPane1.setViewportView(jobListings);

        returnBtn.setText("Return to View");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        applyJob.setText("Apply");
        applyJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyJobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(returnBtn)
                        .addGap(18, 18, 18)
                        .addComponent(applyJob)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnBtn)
                    .addComponent(applyJob))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        if (DB.userType(user).equals("recruiter")) {
            RecruiterView newScreen = new RecruiterView(DB, user);
            newScreen.setVisible(true);
        } else {
            ApplicantView newScreen = new ApplicantView(DB, user);
            newScreen.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_returnBtnActionPerformed

    private void applyJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyJobActionPerformed
        // Index of selected element 
        String chosenJob = jobs.get(listJobs.getSelectedIndex()).split(":")[0];
        applyToJob newScreen = new applyToJob(DB, user, chosenJob);
        newScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_applyJobActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyJob;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jobListings;
    private javax.swing.JButton returnBtn;
    // End of variables declaration//GEN-END:variables
}
